# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-esb-db
  labels:
    name: mysql-esb-db
spec:
  replicas: 1
  selector:
    name: mysql-esb-db
  template:
    metadata:
      labels:
        name: mysql-esb-db
    spec:
      containers:
      - name: mysql-esb-db
        image: mysql:5.5
        env:
        -
          name: MYSQL_ROOT_PASSWORD
          value: root
        -
          name: MYSQL_DATABASE
          value: ESB_DB
        -
          name: MYSQL_USER
          value: wso2carbon
        -
          name: MYSQL_PASSWORD
          value: wso2carbon
        ports:
        -
          containerPort: 3306
          protocol: "TCP"
